name: Membrane RPM Test
description: Test

inputs:
  who-to-greet:
    description: Who to greet
    required: true
    default: World

outputs:
  time:
    description: A time

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.who-to-greet }}
