on: [push]

jobs:
  build-rpm:
    runs-on: ubuntu-latest
    name: Build RPM
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Containerized RPM Build
        uses: ./
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: rpms
          path: ${{ github.workspace }}/artifacts
