on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Hello
        id: hello
        uses: actions/hello-world-docker-action@v2
        with:
          who-to-greet: "fooman"
      - name: Get output
        run: echo "Time was ${{ steps.hello.outputs.time }}"
